"""initial

Revision ID: 8293b6ef7e05
Revises: 
Create Date: 2026-03-06 09:19:25.041343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8293b6ef7e05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('voter_status', sa.String(length=50), nullable=False),
    sa.Column('candidate_status', sa.String(length=50), nullable=False),
    sa.Column('resume_path', sa.String(length=500), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('is_roster_member', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)

    op.create_table('nomination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('nominated_by_name', sa.String(length=200), nullable=True),
    sa.Column('nominated_by_phone', sa.String(length=40), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'office_id', name='uq_candidate_office')
    )
    with op.batch_alter_table('nomination', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomination_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomination_office_id'), ['office_id'], unique=False)

    op.create_table('poll_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('is_runoff', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_session_office_id'), ['office_id'], unique=False)

    op.create_table('ballot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('cast_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['poll_session.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'voter_id', name='uq_ballot_one_per_voter_per_session')
    )
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ballot_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ballot_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ballot_voter_id'), ['voter_id'], unique=False)

    op.create_table('objection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomination_id', sa.Integer(), nullable=False),
    sa.Column('filed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('filed_by_name', sa.String(length=200), nullable=True),
    sa.Column('filed_by_phone', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['nomination_id'], ['nomination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objection_filed_by_user_id'), ['filed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objection_nomination_id'), ['nomination_id'], unique=False)

    op.create_table('office_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('winning_round_number', sa.Integer(), nullable=True),
    sa.Column('last_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_session_id'], ['poll_session.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['winner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('office_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_result_last_session_id'), ['last_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_office_result_office_id'), ['office_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_office_result_winner_user_id'), ['winner_user_id'], unique=False)

    op.create_table('session_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['poll_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'candidate_id', name='uq_session_candidate')
    )
    with op.batch_alter_table('session_candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_candidate_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_candidate_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_candidate_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_candidate_candidate_id'))

    op.drop_table('session_candidate')
    with op.batch_alter_table('office_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_result_winner_user_id'))
        batch_op.drop_index(batch_op.f('ix_office_result_office_id'))
        batch_op.drop_index(batch_op.f('ix_office_result_last_session_id'))

    op.drop_table('office_result')
    with op.batch_alter_table('objection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objection_nomination_id'))
        batch_op.drop_index(batch_op.f('ix_objection_filed_by_user_id'))

    op.drop_table('objection')
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ballot_voter_id'))
        batch_op.drop_index(batch_op.f('ix_ballot_session_id'))
        batch_op.drop_index(batch_op.f('ix_ballot_candidate_id'))

    op.drop_table('ballot')
    with op.batch_alter_table('poll_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_session_office_id'))

    op.drop_table('poll_session')
    with op.batch_alter_table('nomination', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomination_office_id'))
        batch_op.drop_index(batch_op.f('ix_nomination_candidate_id'))

    op.drop_table('nomination')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('office')
    # ### end Alembic commands ###
